version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    ports:
      - '${DB_EXPOSED_PORT:-5433}:5432'
    volumes:
      - pg:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    volumes:
      - pgadmin:/root/.pgadmin
      - pgadmin:/var/lib/pgadmin
    ports:
      - '5050:5050'

volumes:
  pg:
  pgadmin: